# Generated by Django 2.2 on 2019-04-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20190410_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='Withdrawal', max_length=16),
        ),
    ]
