# Generated by Django 2.2 on 2019-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_auto_20190409_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Deposit', 'deposit'), ('Withdrawal', 'withdrawal')], default='withdrawal', max_length=16),
        ),
    ]
