# Generated by Django 2.2 on 2019-04-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20190411_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_uploaded',
        ),
    ]
